project:
  type: website
  output-dir: docs

website:
  title: "Tristan Zook"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: capstone.qmd
        text: My Computer Science Capstone
      - text: My 405 Projects
        menu:
          - href: SqlProject.qmd
            text: SQL Project
          - href: TextAnalysis.qmd
            text: "Project 3" 
          - href: rlstatsreadme.qmd
            text: rlstats
          - href: Project5.qmd
            text: Project 5

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



