project:
  type: website
  output-dir: docs

website:
  title: "Tristan Zook"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: My Life as a Student Athlete
      - href: capstone.qmd
        text: My Computer Science Capstone
      - text: My 405 Projects
        menu:
          - href: SqlProject.qmd
            text: Mountaneering Data Analysis with SQL
          - href: TextAnalysis.qmd
            text: TedTalk Text Analysis 
          - href: rlstatsreadme.qmd
            text: rlstats Package
          - href: Project5.qmd
            text: A Layered Grammar of Graphics Paper Review

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



