project:
  type: website
  output-dir: docs
  resources:
    - files/*.pdf

website:
  title: "Tristan Zook"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: My Life as a Student Athlete
      - text: Computer Science Projects  
        menu: 
          - href: capstone.qmd
            text: My Computer Science Capstone
          - href: givvy.qmd
            text: "Givvy: A Charity Donation Web Application Backend"
      - text: Data Science/Statistics Projects
        menu:
          - href: BikeShare.qmd
            text: Machine Learning Bike Share Data Analysis Technical Report
          - href: BikeShareReport.qmd
            text: Machine Learning Bike Share Data Analysis Non-Technical Presentation
          - href: AmazonLegoDataAnalysis.qmd
            text: Amazon Lego Statistical Modeling
          - href: SqlProject.qmd
            text: Mountaneering Data Analysis with SQL
          - href: TextAnalysis.qmd
            text: TedTalk Text Analysis 
          - href: rlstatsreadme.qmd
            text: rlstats Package
          - href: Project5.qmd
            text: A Layered Grammar of Graphics Paper Review
      - text: Mathematics Projects
        menu: 
          - href: probexp.qmd
            text: Probability Scenario Simulation and Analysis
          - href: mathcapstone.qmd
            text: My Mathematics Capstone
          - href: mbp.qmd
            text: The Mighty Big Problem



format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



